name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
                       Welcome to `hive`!
                       If this is a security issue or vulnerability, please email me at code.dishb@gmail.com and close this issue.
                       Thank you for contributing!
        pr-message: |
                    Welcome to `hive`!
                    Please remember to read the CONTRIBUTING.md file and follow the commit style guide from dishb/commit-styles.
                    Thank you for contributing!
